-- Allow authenticated users to insert universities
CREATE POLICY "Authenticated users can add universities" 
ON public.universities 
FOR INSERT 
TO authenticated
WITH CHECK (true);

-- Insert all Bangladesh universities
INSERT INTO public.universities (name, type, location)
VALUES
  -- Public Universities
  ('University of Dhaka', 'public', 'Dhaka'),
  ('Bangladesh University of Engineering and Technology (BUET)', 'public', 'Dhaka'),
  ('Jahangirnagar University', 'public', 'Savar, Dhaka'),
  ('Rajshahi University', 'public', 'Rajshahi'),
  ('Chittagong University', 'public', 'Chittagong'),
  ('Khulna University', 'public', 'Khulna'),
  ('Shahjalal University of Science and Technology', 'public', 'Sylhet'),
  ('Bangladesh Agricultural University', 'public', 'Mymensingh'),
  ('Islamic University', 'public', 'Kushtia'),
  ('Bangabandhu Sheikh Mujibur Rahman Agricultural University', 'public', 'Gazipur'),
  ('Bangabandhu Sheikh Mujibur Rahman Science and Technology University', 'public', 'Gopalganj'),
  ('Comilla University', 'public', 'Comilla'),
  ('Jagannath University', 'public', 'Dhaka'),
  ('Jatiya Kabi Kazi Nazrul Islam University', 'public', 'Mymensingh'),
  ('Begum Rokeya University', 'public', 'Rangpur'),
  ('Mawlana Bhashani Science and Technology University', 'public', 'Tangail'),
  ('Noakhali Science and Technology University', 'public', 'Noakhali'),
  ('Patuakhali Science and Technology University', 'public', 'Patuakhali'),
  ('Hajee Mohammad Danesh Science and Technology University', 'public', 'Dinajpur'),
  ('Pabna University of Science and Technology', 'public', 'Pabna'),
  ('Jessore University of Science and Technology', 'public', 'Jessore'),
  ('Bangabandhu Sheikh Mujibur Rahman Maritime University', 'public', 'Dhaka'),
  ('Sheikh Hasina University', 'public', 'Netrokona'),
  ('Rangamati Science and Technology University', 'public', 'Rangamati'),
  ('Rabindra University', 'public', 'Shahjadpur, Sirajganj'),
  ('Barishal University', 'public', 'Barishal'),
  ('Sher-e-Bangla Agricultural University', 'public', 'Dhaka'),
  ('Sylhet Agricultural University', 'public', 'Sylhet'),
  ('Chattogram Veterinary and Animal Sciences University', 'public', 'Chittagong'),
  ('Bangladesh University of Professionals', 'public', 'Dhaka'),
  ('National University, Bangladesh', 'public', 'Gazipur'),
  ('Bangladesh Open University', 'public', 'Gazipur'),
  ('Islamic Arabic University', 'public', 'Dhaka'),
  ('Bangladesh University of Textiles', 'public', 'Dhaka'),
  
  -- Private Universities
  ('North South University', 'private', 'Dhaka'),
  ('BRAC University', 'private', 'Dhaka'),
  ('Independent University, Bangladesh', 'private', 'Dhaka'),
  ('East West University', 'private', 'Dhaka'),
  ('American International University-Bangladesh (AIUB)', 'private', 'Dhaka'),
  ('United International University', 'private', 'Dhaka'),
  ('Daffodil International University', 'private', 'Dhaka'),
  ('AUST (Ahsanullah University of Science and Technology)', 'private', 'Dhaka'),
  ('Stamford University Bangladesh', 'private', 'Dhaka'),
  ('University of Liberal Arts Bangladesh (ULAB)', 'private', 'Dhaka'),
  ('University of Asia Pacific', 'private', 'Dhaka'),
  ('Primeasia University', 'private', 'Dhaka'),
  ('Green University of Bangladesh', 'private', 'Dhaka'),
  ('City University, Bangladesh', 'private', 'Dhaka'),
  ('State University of Bangladesh', 'private', 'Dhaka'),
  ('Northern University Bangladesh', 'private', 'Dhaka'),
  ('Southeast University', 'private', 'Dhaka'),
  ('Uttara University', 'private', 'Dhaka'),
  ('World University of Bangladesh', 'private', 'Dhaka'),
  ('Bangladesh University', 'private', 'Dhaka'),
  ('Presidency University', 'private', 'Dhaka'),
  ('University of Development Alternative (UODA)', 'private', 'Dhaka'),
  ('The People''s University of Bangladesh', 'private', 'Dhaka'),
  ('Prime University', 'private', 'Dhaka'),
  ('Shanto-Mariam University of Creative Technology', 'private', 'Dhaka'),
  ('Manarat International University', 'private', 'Dhaka'),
  ('International University of Business Agriculture and Technology (IUBAT)', 'private', 'Dhaka'),
  ('Eastern University', 'private', 'Dhaka'),
  ('Bangladesh Islami University', 'private', 'Dhaka'),
  ('Bangladesh University of Business and Technology (BUBT)', 'private', 'Dhaka'),
  ('Dhaka International University', 'private', 'Dhaka'),
  ('Gono Bishwabidyalay (Peoples University)', 'private', 'Savar, Dhaka'),
  ('International Islamic University Chittagong', 'private', 'Chittagong'),
  ('Premier University', 'private', 'Chittagong'),
  ('Southern University Bangladesh', 'private', 'Chittagong'),
  ('University of Science and Technology Chittagong (USTC)', 'private', 'Chittagong'),
  ('BGC Trust University Bangladesh', 'private', 'Chittagong'),
  ('Port City International University', 'private', 'Chittagong'),
  ('Central Women''s University', 'private', 'Dhaka'),
  ('Asian University for Women', 'private', 'Chittagong'),
  ('Metropolitan University', 'private', 'Sylhet'),
  ('Leading University', 'private', 'Sylhet'),
  ('Sylhet International University', 'private', 'Sylhet'),
  ('North Western University', 'private', 'Khulna'),
  ('North Bengal International University', 'private', 'Rajshahi'),
  ('Varendra University', 'private', 'Rajshahi'),
  ('Royal University of Dhaka', 'private', 'Dhaka'),
  ('Notre Dame University Bangladesh', 'private', 'Dhaka'),
  ('Canadian University of Bangladesh', 'private', 'Dhaka'),
  ('Sonargaon University', 'private', 'Dhaka'),
  ('University of Information Technology and Sciences (UITS)', 'private', 'Dhaka'),
  ('Victoria University of Bangladesh', 'private', 'Dhaka'),
  ('Z.H. Sikder University of Science and Technology', 'private', 'Shariatpur'),
  ('Britannia University', 'private', 'Comilla'),
  ('Cox''s Bazar International University', 'private', 'Cox''s Bazar'),
  ('Feni University', 'private', 'Feni'),
  ('Global University Bangladesh', 'private', 'Barishal'),
  ('Ishakha International University', 'private', 'Kishoreganj'),
  ('Khwaja Yunus Ali University', 'private', 'Sirajganj'),
  ('Ranada Prasad Shaha University', 'private', 'Narayanganj'),
  ('Times University Bangladesh', 'private', 'Faridpur'),
  ('Hamdard University Bangladesh', 'private', 'Munshiganj'),
  ('Exim Bank Agricultural University Bangladesh', 'private', 'Chapainawabganj'),
  ('Trust University, Barishal', 'private', 'Barishal'),
  ('First Capital University of Bangladesh', 'private', 'Chuadanga')
ON CONFLICT DO NOTHING;