// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqrfivjscjaacafdmosk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcmZpdmpzY2phYWNhZmRtb3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNDgwNTAsImV4cCI6MjA4NDcyNDA1MH0.PhGSuet73CGRm5OnNSITezh2xKcxXYVSccFJsz1e3n0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});